apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: video-player
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: video-player
spec:
  selector:
    app.kubernetes.io/name: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
