apiVersion: v1
kind: Secret
metadata:
  name: videoplayer-secrets
  namespace: video-player
type: Opaque
stringData:
  mysql-root-password: replace-with-local-mysql-password
  database-url: mysql://root:replace-with-local-mysql-password@mysql:3306/video_player
  jwt-secret: replace-with-random-jwt-secret
  admin-secret: replace-with-random-admin-secret
