export const SITE_KNOWLEDGE_SOURCES = [
  'README.md',
  'DESIGN.md',
  'docs/API文档-V1.md',
  'docs/4组-软件详细设计说明书.md',
  'frontend/src/router/index.ts',
  'frontend/src/views/upload/UploadView.vue',
  'frontend/src/views/live/LiveRoomView.vue',
  'frontend/src/views/search/SearchView.vue',
  'frontend/src/views/video/VideoDetailView.vue',
  'frontend/src/views/creator/CreatorDashboardView.vue',
  'frontend/src/components/AppHeader.vue',
  'frontend/src/api/platform.ts',
  'backend/src/modules/video/video.controller.ts',
  'backend/src/modules/video/video.service.ts',
  'backend/src/modules/search/search.controller.ts',
  'backend/src/modules/search/search.service.ts',
  'backend/src/modules/live/live.controller.ts',
  'backend/src/modules/live/live.service.ts',
  'backend/src/modules/comment/comment.controller.ts',
  'backend/src/modules/comment/comment.service.ts',
  'backend/src/modules/admin/admin.controller.ts',
  'backend/src/modules/admin/admin.module.ts',
] as const;
