CREATE TABLE `VideoReview` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `videoId` VARCHAR(191) NOT NULL,
  `reviewerId` INTEGER NULL,
  `requestId` VARCHAR(128) NOT NULL,
  `status` ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
  `reason` VARCHAR(255) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `reviewedAt` DATETIME(3) NULL,
  UNIQUE INDEX `VideoReview_requestId_key`(`requestId`),
  INDEX `VideoReview_videoId_createdAt_idx`(`videoId`, `createdAt`),
  INDEX `VideoReview_status_createdAt_idx`(`status`, `createdAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `CommentAiTask` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `targetType` ENUM('VIDEO', 'COMMENT', 'VIDEO_DANMAKU') NOT NULL,
  `targetId` VARCHAR(191) NOT NULL,
  `videoId` VARCHAR(191) NULL,
  `requesterId` INTEGER NOT NULL,
  `requestId` VARCHAR(128) NOT NULL,
  `prompt` VARCHAR(1000) NOT NULL,
  `status` ENUM('PENDING', 'RUNNING', 'SUCCESS', 'FAILED') NOT NULL DEFAULT 'PENDING',
  `attempts` INTEGER NOT NULL DEFAULT 0,
  `lastError` VARCHAR(1024) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `completedAt` DATETIME(3) NULL,
  UNIQUE INDEX `CommentAiTask_requestId_key`(`requestId`),
  INDEX `CommentAiTask_targetType_targetId_createdAt_idx`(`targetType`, `targetId`, `createdAt`),
  INDEX `CommentAiTask_status_updatedAt_idx`(`status`, `updatedAt`),
  INDEX `CommentAiTask_requesterId_createdAt_idx`(`requesterId`, `createdAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ReportRecord` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `reporterId` INTEGER NOT NULL,
  `handlerId` INTEGER NULL,
  `targetType` ENUM('VIDEO', 'COMMENT', 'VIDEO_DANMAKU') NOT NULL,
  `targetId` VARCHAR(191) NOT NULL,
  `videoId` VARCHAR(191) NULL,
  `targetSnapshot` JSON NULL,
  `pendingKey` VARCHAR(160) NULL,
  `requestId` VARCHAR(128) NOT NULL,
  `reason` VARCHAR(255) NOT NULL,
  `status` ENUM('PENDING', 'PROCESSED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
  `handleNote` VARCHAR(255) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  `handledAt` DATETIME(3) NULL,
  UNIQUE INDEX `ReportRecord_pendingKey_key`(`pendingKey`),
  UNIQUE INDEX `ReportRecord_requestId_key`(`requestId`),
  INDEX `ReportRecord_status_createdAt_idx`(`status`, `createdAt`),
  INDEX `ReportRecord_targetType_targetId_createdAt_idx`(`targetType`, `targetId`, `createdAt`),
  INDEX `ReportRecord_reporterId_createdAt_idx`(`reporterId`, `createdAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ModerationDecision` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `decisionId` VARCHAR(128) NOT NULL,
  `requestId` VARCHAR(128) NOT NULL,
  `targetType` ENUM('VIDEO', 'COMMENT', 'VIDEO_DANMAKU') NOT NULL,
  `targetId` VARCHAR(191) NOT NULL,
  `videoId` VARCHAR(191) NULL,
  `decision` ENUM('APPROVE', 'REJECT', 'KEEP', 'HIDE', 'DELETE') NULL,
  `reason` VARCHAR(255) NULL,
  `operatorId` INTEGER NULL,
  `applyStatus` ENUM('PENDING', 'DECIDED', 'APPLY_PENDING', 'APPLIED', 'APPLY_FAILED_RETRYABLE', 'APPLY_FAILED_FINAL') NOT NULL DEFAULT 'PENDING',
  `attempts` INTEGER NOT NULL DEFAULT 0,
  `lastError` VARCHAR(1024) NULL,
  `decidedAt` DATETIME(3) NULL,
  `appliedAt` DATETIME(3) NULL,
  `nextRetryAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `ModerationDecision_decisionId_key`(`decisionId`),
  UNIQUE INDEX `ModerationDecision_requestId_key`(`requestId`),
  INDEX `ModerationDecision_targetType_targetId_createdAt_idx`(`targetType`, `targetId`, `createdAt`),
  INDEX `ModerationDecision_applyStatus_nextRetryAt_idx`(`applyStatus`, `nextRetryAt`),
  INDEX `ModerationDecision_operatorId_createdAt_idx`(`operatorId`, `createdAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
